import Finance from "../models/financeModel.js";
import Fee from "../models/feeModel.js";
import Salary from "../models/salaryModel.js";
import FamilyFee from "../models/familyFeeModel.js";

export const AddFinance = async ( req, res ) => {
  try {

    const { income , expenses , debt  , date } = req.body;

    if (!income || !expenses || !debt || !date) {
      return res.status(400).json({ message: "Fadlan buuxi dhammaan meelaha banan" });
    }

    


    const finance = new Finance({
      income,
      expenses,
      debt,
      date: date ? new Date(date) : new Date()
    });


    await finance.save();

    return res.status(201).json({ message: "Maalgelinta si guul leh ayaa loo abuuray", finance });
  } catch (error) {
    console.error("error in AddFinance function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

// Auto-generate monthly finance summary
export const generateMonthlyFinance = async (req, res) => {
  try {
    const { month, year } = req.body;
    
    if (!month || !year) {
      return res.status(400).json({ message: "Fadlan buuxi bisha iyo sanadka" });
    }

    const monthNum = parseInt(month);
    const yearNum = parseInt(year);

    // Calculate total student fees (income) for the month
    const studentFeesResult = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum, 
          paid: true 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    // Include Family Fees paid amounts as income
    const familyPaidResult = await FamilyFee.aggregate([
      { $match: { month: monthNum, year: yearNum } },
      { $group: { _id: null, total: { $sum: "$paidAmount" } } }
    ]);

    const totalIncome = (studentFeesResult.length > 0 ? studentFeesResult[0].total : 0)
                      + (familyPaidResult.length > 0 ? familyPaidResult[0].total : 0);
    const paidFeesCount = studentFeesResult.length > 0 ? studentFeesResult[0].count : 0;

    // Calculate total teacher salaries (expenses) for the month
    const teacherSalariesResult = await Salary.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum, 
          paid: true 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$totalAmount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    const totalExpenses = teacherSalariesResult.length > 0 ? teacherSalariesResult[0].total : 0;
    const paidSalariesCount = teacherSalariesResult.length > 0 ? teacherSalariesResult[0].count : 0;

    // Calculate unpaid fees (debt)
    const unpaidFeesResult = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum, 
          paid: false 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    // Include Family Fees remaining amounts as debt
    const familyDebtResult = await FamilyFee.aggregate([
      { $match: { month: monthNum, year: yearNum } },
      { $project: { remaining: { $subtract: ["$totalAmount", { $ifNull: ["$paidAmount", 0] }] } } },
      { $match: { remaining: { $gt: 0 } } },
      { $group: { _id: null, total: { $sum: "$remaining" } } }
    ]);

    const totalDebt = (unpaidFeesResult.length > 0 ? unpaidFeesResult[0].total : 0)
                    + (familyDebtResult.length > 0 ? familyDebtResult[0].total : 0);
    const unpaidFeesCount = unpaidFeesResult.length > 0 ? unpaidFeesResult[0].count : 0;

    // Check if finance record already exists for this month
    const existingFinance = await Finance.findOne({
      month: monthNum,
      year: yearNum
    });

    if (existingFinance) {
      // Update existing record
      existingFinance.income = totalIncome;
      existingFinance.expenses = totalExpenses;
      existingFinance.debt = totalDebt;
      existingFinance.paidFeesCount = paidFeesCount;
      existingFinance.paidSalariesCount = paidSalariesCount;
      existingFinance.unpaidFeesCount = unpaidFeesCount;
      existingFinance.lastUpdated = new Date();
      
      await existingFinance.save();
      
      return res.status(200).json({ 
        message: "Maalgelinta bishan si guul leh ayaa loo cusboonaysiiyay", 
        finance: existingFinance 
      });
    } else {
      // Create new finance record
      const finance = new Finance({
        income: totalIncome,
        expenses: totalExpenses,
        debt: totalDebt,
        month: monthNum,
        year: yearNum,
        paidFeesCount,
        paidSalariesCount,
        unpaidFeesCount,
        date: new Date(yearNum, monthNum - 1, 1),
        isAutoGenerated: true
      });

      await finance.save();

      return res.status(201).json({ 
        message: "Maalgelinta bishan si guul leh ayaa loo abuuray", 
        finance 
      });
    }
  } catch (error) {
    console.error("error in generateMonthlyFinance function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

export const getAllFinance = async ( req, res ) => {
  try {
    const finance = await Finance.find({}).sort({ createdAt: -1 });

    return res.status(200).json({ message: "Maalgelinta si guul leh ayaa loo helay", finance });
  } catch (error) {
    console.error("error in getAllFinance function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

// Get finance summary with detailed breakdown
export const getFinanceSummary = async (req, res) => {
  try {
    const { month, year } = req.query;
    
    if (!month || !year) {
      return res.status(400).json({ message: "Fadlan dooro bisha iyo sanadka" });
    }

    const monthNum = parseInt(month);
    const yearNum = parseInt(year);

    // Get total student fees for the month (income)
    const studentFeesTotal = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum, 
          paid: true 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    // Family fees income
    const familyPaidTotal = await FamilyFee.aggregate([
      { $match: { month: monthNum, year: yearNum } },
      { $group: { _id: null, total: { $sum: "$paidAmount" } } }
    ]);

    // Get total teacher salaries for the month (expenses)
    const teacherSalariesTotal = await Salary.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum, 
          paid: true 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$totalAmount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    // Get unpaid fees (debt)
    const unpaidFeesTotal = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum, 
          paid: false 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    const familyDebtTotal = await FamilyFee.aggregate([
      { $match: { month: monthNum, year: yearNum } },
      { $project: { remaining: { $subtract: ["$totalAmount", { $ifNull: ["$paidAmount", 0] }] } } },
      { $match: { remaining: { $gt: 0 } } },
      { $group: { _id: null, total: { $sum: "$remaining" } } }
    ]);

    // Get manual finance records for the month
    const startDate = new Date(yearNum, monthNum - 1, 1);
    const endDate = new Date(yearNum, monthNum, 0);
    
    const manualFinance = await Finance.find({
      date: { $gte: startDate, $lte: endDate },
      isAutoGenerated: { $ne: true }
    }).sort({ createdAt: -1 });

    // Get auto-generated finance record for the month
    const autoFinance = await Finance.findOne({
      month: monthNum,
      year: yearNum,
      isAutoGenerated: true
    });

    const summary = {
      month: monthNum,
      year: yearNum,
      income: (studentFeesTotal.length > 0 ? studentFeesTotal[0].total : 0) + (familyPaidTotal.length > 0 ? familyPaidTotal[0].total : 0),
      expenses: teacherSalariesTotal.length > 0 ? teacherSalariesTotal[0].total : 0,
      debt: (unpaidFeesTotal.length > 0 ? unpaidFeesTotal[0].total : 0) + (familyDebtTotal.length > 0 ? familyDebtTotal[0].total : 0),
      paidFeesCount: studentFeesTotal.length > 0 ? studentFeesTotal[0].count : 0,
      paidSalariesCount: teacherSalariesTotal.length > 0 ? teacherSalariesTotal[0].count : 0,
      unpaidFeesCount: unpaidFeesTotal.length > 0 ? unpaidFeesTotal[0].count : 0,
      manualFinance,
      autoFinance,
      netProfit: ((studentFeesTotal.length > 0 ? studentFeesTotal[0].total : 0) + (familyPaidTotal.length > 0 ? familyPaidTotal[0].total : 0)) - 
                 (teacherSalariesTotal.length > 0 ? teacherSalariesTotal[0].total : 0)
    };

    return res.status(200).json({ 
      message: "Faahfaahinta maalgelinta si guul leh ayaa loo helay", 
      summary 
    });
  } catch (error) {
    console.error("error in getFinanceSummary function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

// Get monthly breakdown for the entire year
export const getYearlyFinanceBreakdown = async (req, res) => {
  try {
    const { year } = req.query;
    
    if (!year) {
      return res.status(400).json({ message: "Fadlan dooro sanadka" });
    }

    const yearNum = parseInt(year);

    // Get monthly breakdown of student fees
    const monthlyFees = await Fee.aggregate([
      { 
        $match: { 
          year: yearNum, 
          paid: true 
        } 
      },
      { 
        $group: { 
          _id: "$month", 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Include monthly Family Fees income
    const monthlyFamilyPaid = await FamilyFee.aggregate([
      { $match: { year: yearNum } },
      { $group: { _id: "$month", total: { $sum: "$paidAmount" } } },
      { $sort: { _id: 1 } }
    ]);

    // Get monthly breakdown of teacher salaries
    const monthlySalaries = await Salary.aggregate([
      { 
        $match: { 
          year: yearNum, 
          paid: true 
        } 
      },
      { 
        $group: { 
          _id: "$month", 
          total: { $sum: "$totalAmount" },
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Get monthly breakdown of unpaid fees
    const monthlyUnpaidFees = await Fee.aggregate([
      { 
        $match: { 
          year: yearNum, 
          paid: false 
        } 
      },
      { 
        $group: { 
          _id: "$month", 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Include monthly Family Fees debt
    const monthlyFamilyDebt = await FamilyFee.aggregate([
      { $match: { year: yearNum } },
      { $project: { month: 1, remaining: { $subtract: ["$totalAmount", { $ifNull: ["$paidAmount", 0] }] } } },
      { $match: { remaining: { $gt: 0 } } },
      { $group: { _id: "$month", total: { $sum: "$remaining" } } },
      { $sort: { _id: 1 } }
    ]);

    // Create monthly breakdown
    const monthlyBreakdown = [];
    for (let month = 1; month <= 12; month++) {
      const feesData = monthlyFees.find(f => f._id === month) || { total: 0, count: 0 };
      const familyPaidData = monthlyFamilyPaid.find(f => f._id === month) || { total: 0 };
      const salariesData = monthlySalaries.find(s => s._id === month) || { total: 0, count: 0 };
      const unpaidData = monthlyUnpaidFees.find(u => u._id === month) || { total: 0, count: 0 };
      const familyDebtData = monthlyFamilyDebt.find(u => u._id === month) || { total: 0 };

      monthlyBreakdown.push({
        month,
        income: (feesData.total || 0) + (familyPaidData.total || 0),
        expenses: salariesData.total,
        debt: (unpaidData.total || 0) + (familyDebtData.total || 0),
        paidFeesCount: feesData.count,
        paidSalariesCount: salariesData.count,
        unpaidFeesCount: unpaidData.count,
        netProfit: ((feesData.total || 0) + (familyPaidData.total || 0)) - salariesData.total
      });
    }

    return res.status(200).json({ 
      message: "Faahfaahinta maalgelinta sanadka si guul leh ayaa loo helay", 
      yearlyBreakdown: {
        year: yearNum,
        monthlyBreakdown,
        totalIncome: monthlyBreakdown.reduce((sum, m) => sum + (m.income || 0), 0),
        totalExpenses: monthlyBreakdown.reduce((sum, m) => sum + (m.expenses || 0), 0),
        totalDebt: monthlyBreakdown.reduce((sum, m) => sum + (m.debt || 0), 0),
        totalPaidFees: monthlyFees.reduce((sum, f) => sum + f.count, 0),
        totalPaidSalaries: monthlySalaries.reduce((sum, s) => sum + s.count, 0),
        totalUnpaidFees: monthlyUnpaidFees.reduce((sum, u) => sum + u.count, 0)
      }
    });
  } catch (error) {
    console.error("error in getYearlyFinanceBreakdown function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

export const getFinanceById = async ( req, res ) => {
  try {
    const { financeId } = req.params;

    const finance = await Finance.findById(financeId);

    if (!finance) {
      return res.status(404).json({ message: "Maalgelinta lama helin" });
    }

    return res.status(200).json({ message: "Maalgelinta si guul leh ayaa loo helay", finance });
  } catch (error) {
    console.error("error in getFinanceById function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

